# Generated by Django 6.0.7 on 2026-07-18 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'galleribild',
                'verbose_name_plural': 'galleribilder',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SeasonTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='seasons/')),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'säsongstips',
                'verbose_name_plural': 'säsongstips',
                'ordering': ['month'],
            },
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('home', 'Startsida'), ('salon', 'Salongen'), ('treatments', 'Behandlingar'), ('seasons', 'Året runt'), ('gallery', 'Galleri'), ('booking', 'Boka')], max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True, help_text='Huvudtext. Använd tom rad för nytt stycke.')),
                ('hero_image', models.ImageField(blank=True, upload_to='pages/')),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'sida',
                'verbose_name_plural': 'sidor',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='EGentid Spa & Resurs', max_length=120)),
                ('tagline', models.CharField(default='Skönhet & avkoppling – med en värmande touch!', max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='brand/')),
                ('email', models.EmailField(blank=True, default='info@egentidsparesurs.se', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('opening_hours', models.TextField(blank=True, help_text='Visas i sidfoten. En rad per dag eller fritext.')),
                ('footer_text', models.TextField(blank=True, default='En lugn oas för fotvård, handvård och värmande behandlingar.')),
            ],
            options={
                'verbose_name': 'webbplatsinställningar',
                'verbose_name_plural': 'webbplatsinställningar',
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='blocks/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='cms.sitepage')),
            ],
            options={
                'verbose_name': 'innehållsblock',
                'verbose_name_plural': 'innehållsblock',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
