# Generated by Django 6.0.7 on 2026-07-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Hela länken, t.ex. https://www.facebook.com/din-sida'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Hela länken, t.ex. https://www.linkedin.com/in/ditt-namn'),
        ),
    ]
