# Generated by Django 6.0.7 on 2026-07-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_site_settings_social_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='key',
            field=models.CharField(choices=[('home', 'Startsida'), ('salon', 'Salongen'), ('treatments', 'Behandlingar'), ('seasons', 'Året runt'), ('gallery', 'Galleri'), ('booking', 'Boka'), ('contact', 'Kontakt')], max_length=32, unique=True),
        ),
    ]
