# Generated by Django 6.0.7 on 2026-07-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_contact_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepage',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Valfri meta description för denna sida.', max_length=160),
        ),
        migrations.AddField(
            model_name='sitepage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Valfri SEO-titel (annars används sidans titel).', max_length=70),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_description',
            field=models.CharField(blank=True, default='Fotvård, spa-pedikyr och värmande manikyr. Boka egentid hos EGentid Spa & Resurs.', help_text='Standard meta description (ca 150–160 tecken) om sidan saknar egen.', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Delningsbild för sociala medier (valfritt). Annars används logotyp/hero.', upload_to='seo/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='public_site_url',
            field=models.URLField(blank=True, help_text='Publik bas-URL utan avslutande snedstreck, t.ex. https://egentidsparesurs.se'),
        ),
    ]
