# Generated by Django 6.0.7 on 2026-08-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_seo_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasontip',
            name='body',
            field=models.TextField(help_text='Månadens innehåll. Använd ## för underrubrik, ✔ för checklista, och tom rad mellan stycken. Byt text varje månad här.'),
        ),
        migrations.AlterField(
            model_name='seasontip',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Mars'), (4, 'April'), (5, 'Maj'), (6, 'Juni'), (7, 'Juli'), (8, 'Augusti'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'December')], unique=True),
        ),
        migrations.AlterField(
            model_name='seasontip',
            name='title',
            field=models.CharField(help_text='T.ex. “Juli – Ge händer och fötter lite extra sommaromsorg”.', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitepage',
            name='key',
            field=models.CharField(choices=[('home', 'Startsida'), ('salon', 'Om'), ('treatments', 'Behandlingar'), ('warming', 'Värmande behandlingar'), ('prices', 'Prislista'), ('seasons', 'Året runt'), ('gallery', 'Galleri'), ('booking', 'Boka'), ('contact', 'Kontakt'), ('service', 'Service')], max_length=32, unique=True),
        ),
    ]
