# Generated by Django 6.0.7 on 2026-07-19 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_seo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasontip',
            name='icon',
            field=models.CharField(blank=True, default='🌱', help_text='Emoji eller symbol framför månadsrubriken.', max_length=8),
        ),
        migrations.AddField(
            model_name='seasontip',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Visa detta tipset på Året runt-sidan. Endast ett kan vara valt.', verbose_name='Visas på Året runt'),
        ),
        migrations.AlterField(
            model_name='seasontip',
            name='body',
            field=models.TextField(blank=True, help_text='Valfri brödtext. Punkter läggs till under Tipspunkter.'),
        ),
        migrations.AlterField(
            model_name='seasontip',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Mars'), (4, 'April'), (5, 'Maj'), (6, 'Juni'), (7, 'Juli'), (8, 'Augusti'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'December')], help_text='Vilken kalendermånad tipset hör till.', unique=True),
        ),
        migrations.AlterField(
            model_name='seasontip',
            name='title',
            field=models.CharField(help_text='Rubrik under introtexten, t.ex. Mars – Vårens första månad', max_length=200),
        ),
        migrations.CreateModel(
            name='SeasonTipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.seasontip')),
            ],
            options={
                'verbose_name': 'tipspunkt',
                'verbose_name_plural': 'tipspunkter',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
