# Generated by Django 6.0.7 on 2026-07-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_season_tip_featured_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasontip',
            name='closing_body',
            field=models.CharField(blank=True, help_text='Text efter etiketten, före bokningslänken.', max_length=300),
        ),
        migrations.AddField(
            model_name='seasontip',
            name='closing_cta',
            field=models.CharField(blank=True, default='boka din behandling nu!', help_text='Fet länkad text till Boka-sidan. Tom = ingen länk.', max_length=80),
        ),
        migrations.AddField(
            model_name='seasontip',
            name='closing_icon',
            field=models.CharField(blank=True, default='💡', help_text='Emoji framför avslutningen, t.ex. 💡', max_length=8),
        ),
        migrations.AddField(
            model_name='seasontip',
            name='closing_label',
            field=models.CharField(blank=True, default='Kort sagt:', help_text='Fet stil i början, t.ex. Kort sagt:', max_length=40),
        ),
        migrations.AlterField(
            model_name='seasontip',
            name='body',
            field=models.TextField(blank=True, help_text='Valfri brödtext ovanför tipspunkterna.'),
        ),
    ]
