# Generated by Django 5.2.12 on 2026-08-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_season_tip_closing'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Mars'), (4, 'April'), (5, 'Maj'), (6, 'Juni'), (7, 'Juli'), (8, 'Augusti'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'December')], help_text='Vilken kalendermånad blocket hör till.', unique=True)),
                ('icon', models.CharField(blank=True, default='', help_text='Emoji framför månadsnamnet, t.ex. 🌾', max_length=8)),
                ('quote', models.CharField(help_text='Citatet i kursiv stil (utan citationstecken — de läggs till i mallen).', max_length=300)),
                ('body', models.TextField(help_text='Stödtext under citatet.')),
                ('cta', models.CharField(help_text='Länktext under texten (går till Boka), t.ex. Återhämtande fotvård', max_length=200)),
                ('is_visible', models.BooleanField(default=True, help_text='Avmarkera för att dölja denna månad på startsidan.')),
            ],
            options={
                'verbose_name': 'känner du igen',
                'verbose_name_plural': 'känner du igen',
                'ordering': ['month'],
            },
        ),
        migrations.AlterField(
            model_name='sitepage',
            name='key',
            field=models.CharField(choices=[('home', 'Startsida'), ('salon', 'Om'), ('treatments', 'Behandlingar'), ('warming', 'Värmande behandlingar'), ('prices', 'Prislista'), ('seasons', 'Året runt'), ('gallery', 'Galleri'), ('booking', 'Boka'), ('contact', 'Kontakt'), ('service', 'Service')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='opening_hours',
            field=models.TextField(blank=True, help_text='Valfri extratext under veckoschemat i sidfoten (t.ex. ”Bokning krävs”). Själva tiderna kommer från Veckoschema.'),
        ),
    ]
