# Generated by Django 5.2.12 on 2026-08-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_month_hook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='key',
            field=models.CharField(choices=[('home', 'Startsida'), ('salon', 'Om'), ('treatments', 'Behandlingar & priser'), ('warming', 'Värmande behandlingar'), ('prices', 'Prislista'), ('seasons', 'Året runt'), ('gallery', 'Galleri'), ('booking', 'Boka'), ('contact', 'Kontakt'), ('service', 'Service')], max_length=32, unique=True),
        ),
    ]
