# Generated by Django 5.2.12 on 2026-08-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_treatments_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='opening_hours',
            field=models.TextField(blank=True, help_text='Används inte i sidfoten just nu. Sidfoten visar i stället ”Välkommen att boka tid under Boka” med länk till bokning.'),
        ),
    ]
