# Generated by Django 5.2.12 on 2026-08-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_opening_hours_helptext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasontip',
            name='body',
            field=models.TextField(blank=True, help_text='Huvudtexten på Året runt för denna månad. ## = underrubrik, • eller ✔ = punktlista.'),
        ),
        migrations.AlterField(
            model_name='seasontip',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Används inte längre. Året runt visar automatiskt innevarande kalendermånad utifrån fältet Månad.', verbose_name='Visas på Året runt (äldre)'),
        ),
    ]
