# Generated by Django 5.2.12 on 2026-08-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_season_tip_body_helptext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthhook',
            name='body',
            field=models.TextField(help_text='Stödtext under citatet. Fet stil: skriv **text** (dubbla asterisker runt ordet).'),
        ),
        migrations.AlterField(
            model_name='monthhook',
            name='cta',
            field=models.CharField(help_text='Länktext under texten (går till Boka), t.ex. Återhämtande fotvård. Fet stil: skriv **text** (dubbla asterisker runt ordet).', max_length=200),
        ),
        migrations.AlterField(
            model_name='monthhook',
            name='quote',
            field=models.CharField(help_text='Citatet i kursiv stil (utan citationstecken — de läggs till i mallen). Fet stil: skriv **text** (dubbla asterisker runt ordet).', max_length=300),
        ),
        migrations.AlterField(
            model_name='seasontip',
            name='body',
            field=models.TextField(blank=True, help_text='Huvudtexten på Året runt för denna månad. ## = underrubrik, • eller ✔ = punktlista. Fet stil: skriv **text** (dubbla asterisker runt ordet).'),
        ),
        migrations.AlterField(
            model_name='sitepage',
            name='body',
            field=models.TextField(blank=True, help_text='Huvudtext. Använd tom rad för nytt stycke. Fet stil: skriv **text** (dubbla asterisker runt ordet).'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, help_text='Fet stil: skriv **text** (dubbla asterisker runt ordet).'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(blank=True, default='En lugn oas för fotvård, handvård och värmande behandlingar.', help_text='Fet stil: skriv **text** (dubbla asterisker runt ordet).'),
        ),
    ]
