# Generated by Django 5.2.12 on 2026-08-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_bold_markup_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepage',
            name='cta_primary',
            field=models.CharField(blank=True, help_text='Text på huvudknappen (t.ex. Boka). Tom = sidans standardtext.', max_length=120, verbose_name='Huvudknapp'),
        ),
        migrations.AddField(
            model_name='sitepage',
            name='cta_secondary',
            field=models.CharField(blank=True, help_text='Text på den andra knappen (t.ex. Se värmande behandlingar & priser). Tom = ingen extraknapp (utom sidans inbyggda standard).', max_length=120, verbose_name='Extraknapp'),
        ),
        migrations.AlterField(
            model_name='sitepage',
            name='body',
            field=models.TextField(blank=True, help_text='Huvudtext. Tom rad = nytt stycke. ## underrubrik · • eller ✔ punktlista. Fet stil: skriv **text** (dubbla asterisker runt ordet).'),
        ),
    ]
