# Generated by Django 6.0.7 on 2026-07-18 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'stängd dag',
                'verbose_name_plural': 'stängda dagar',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('price_sek', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='services/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'behandling',
                'verbose_name_plural': 'behandlingar',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('is_blocked', models.BooleanField(default=False, help_text='Manuellt blockerad (syns inte som ledig).')),
            ],
            options={
                'verbose_name': 'tidslucka',
                'verbose_name_plural': 'tidsluckor',
                'ordering': ['start'],
                'unique_together': {('start', 'end')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('confirmed', 'Bekräftad'), ('cancelled', 'Avbokad')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.service')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='booking.timeslot')),
            ],
            options={
                'verbose_name': 'bokning',
                'verbose_name_plural': 'bokningar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Måndag'), (1, 'Tisdag'), (2, 'Onsdag'), (3, 'Torsdag'), (4, 'Fredag'), (5, 'Lördag'), (6, 'Söndag')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_minutes', models.PositiveIntegerField(default=60, help_text='Längd per bokningsbart pass i minuter.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'veckoschema',
                'verbose_name_plural': 'veckoschema',
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('weekday', 'start_time', 'end_time')},
            },
        ),
    ]
