# Generated by Django 6.0.7 on 2026-07-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyavailability',
            options={'ordering': ['weekday', 'start_time'], 'verbose_name': 'veckoschema / öppettider', 'verbose_name_plural': 'veckoschema / öppettider'},
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='end_time',
            field=models.TimeField(verbose_name='Stänger'),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Avmarkera för att dölja dagen i sidfoten och vid luckgenerering.', verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='slot_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Längd per bokningsbart pass i minuter (påverkar Boka, inte sidfotens text).', verbose_name='Passlängd (min)'),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='start_time',
            field=models.TimeField(verbose_name='Öppnar'),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Måndag'), (1, 'Tisdag'), (2, 'Onsdag'), (3, 'Torsdag'), (4, 'Fredag'), (5, 'Lördag'), (6, 'Söndag')], verbose_name='Veckodag'),
        ),
    ]
