# Generated by Django 6.0.7 on 2026-08-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_phone_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(max_length=254),
        ),
    ]
