# Generated by Django 6.0.7 on 2026-08-13 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_weekly_availability_verbose_names'),
        ('booking', '0004_booking_notify_channels'),
    ]

    operations = [
    ]
